In [1]:
# import pandas library
import pandas as pd

# read the dataset with name "Emotion_classify_Data.csv" and store it in a variable df
df = pd.read_csv("./datasets/emotion.csv")

# print the shape of dataframe
df.shape

(5937, 2)

In [2]:
# print top 5 rows
df.head(5)

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [3]:
# check the distribution of Emotion
df["Emotion"].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [4]:
# Add the new column "Emotion_num" which gives a unique number to each of these Emotions
# joy --> 0, fear --> 1, anger --> 2
df["Emotion_num"] = df["Emotion"].map({"joy": 0, "fear": 1, "anger": 2})

# checking the results by printing top 5 rows
df

                                                Comment Emotion  Emotion_num
0     i seriously hate one subject to death but now ...    fear            1
1                    im so full of life i feel appalled   anger            2
2     i sit here to write i start to dig out my feel...    fear            1
3     ive been really angry with r and i feel like a...     joy            0
4     i feel suspicious if there is no one outside l...    fear            1
...                                                 ...     ...          ...
5932                 i begun to feel distressed for you    fear            1
5933  i left feeling annoyed and angry thinking that...   anger            2
5934  i were to ever get married i d have everything...     joy            0
5935  i feel reluctant in applying there because i w...    fear            1
5936  i just wanted to apologize to you because i fe...   anger            2

[5937 rows x 3 columns]

### **Modelling without Pre-processing Text data**

In [5]:
# import train-test split
from sklearn.model_selection import train_test_split

X = df["Comment"]
y = df["Emotion_num"]
# Do the 'train-test' splitting with test size of 20%
# Note: Give Random state 2022 and also do the stratify sampling
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [6]:
# print the shapes of X_train and X_test
print(X_train.shape, X_test.shape)

(4749,) (1188,)

**Attempt 1** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**

-   using CountVectorizer with only trigrams.
-   use **RandomForest** as the classifier.
-   print the classification report.

In [18]:
# import CountVectorizer, RandomForest, pipeline, classification_report from sklearn
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report

# 1. create a pipeline object
pipeline = Pipeline(
    [
        ("vectorizer", CountVectorizer(ngram_range=(3, 3))),
        ("model", RandomForestClassifier(n_estimators=100)),
    ]
)

# 2. fit with X_train and y_train
pipeline.fit(X_train, y_train)

# 3. get the predictions for X_test and store it in y_pred
y_hat = pipeline.predict(X_test)

# 4. print the classfication report
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.59      0.19      0.29       400
           1       0.39      0.80      0.53       388
           2       0.54      0.36      0.43       400

    accuracy                           0.45      1188
   macro avg       0.51      0.45      0.42      1188
weighted avg       0.51      0.45      0.42      1188

**Attempt 2** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**

-   using CountVectorizer with both unigram and bigrams.
-   use **Multinomial Naive Bayes** as the classifier.
-   print the classification report.

In [19]:
# import MultinomialNB from sklearn
from sklearn.naive_bayes import MultinomialNB

# 1. create a pipeline object
pipeline = Pipeline(
    [("vectorizer", CountVectorizer(ngram_range=(1, 2))), ("model", MultinomialNB())]
)

# 2. fit with X_train and y_train
pipeline.fit(X_train, y_train)

# 3. get the predictions for X_test and store it in y_pred
y_hat = pipeline.predict(X_test)

# 4. print the classfication report
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.88      0.85      0.87       400
           1       0.84      0.88      0.86       388
           2       0.87      0.85      0.86       400

    accuracy                           0.86      1188
   macro avg       0.86      0.86      0.86      1188
weighted avg       0.86      0.86      0.86      1188

**Attempt 3** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**

-   using CountVectorizer with both unigram and Bigrams.
-   use **RandomForest** as the classifier.
-   print the classification report.

In [20]:
# 1. create a pipeline object
pipeline = Pipeline(
    [
        ("vectorizer", CountVectorizer(ngram_range=(1, 2))),
        ("model", RandomForestClassifier(n_estimators=100)),
    ]
)

# 2. fit with X_train and y_train
pipeline.fit(X_train, y_train)

# 3. get the predictions for X_test and store it in y_pred
y_hat = pipeline.predict(X_test)

# 4. print the classfication report
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89       400
           1       0.94      0.88      0.91       388
           2       0.95      0.85      0.90       400

    accuracy                           0.90      1188
   macro avg       0.91      0.90      0.90      1188
weighted avg       0.91      0.90      0.90      1188

**Attempt 4** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**

-   using **TF-IDF vectorizer** for Pre-processing the text.
-   use **RandomForest** as the classifier.
-   print the classification report.

In [22]:
# import TfidfVectorizer from sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. create a pipeline object
pipeline = Pipeline(
    [
        ("vectorizer", TfidfVectorizer()),
        ("model", RandomForestClassifier(n_estimators=100)),
    ]
)

# 2. fit with X_train and y_train
pipeline.fit(X_train, y_train)

# 3. get the predictions for X_test and store it in y_pred
y_hat = pipeline.predict(X_test)

# 4. print the classfication report
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91       400
           1       0.93      0.91      0.92       388
           2       0.94      0.89      0.91       400

    accuracy                           0.91      1188
   macro avg       0.91      0.91      0.91      1188
weighted avg       0.91      0.91      0.91      1188

<h3>Use text pre-processing to remove stop words, punctuations and apply lemmatization </h3>

In [23]:
import spacy

# load english language model and create nlp object from it
nlp = spacy.load("en_core_web_sm")


# use this utility function to get the preprocessed text data
def preprocess(text):
    # remove stop words and lemmatize the text
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_tokens.append(token.lemma_)

    return " ".join(filtered_tokens)

In [24]:
# create a new column "preprocessed_comment" and use the utility function above to get the clean data
# this will take some time, please be patient
df["preprocessed_comment"] = df["Comment"].apply(preprocess)

**Build a model with pre processed text**

In [25]:
df

,Comment,Emotion,Emotion_num,preprocessed_comment
0,i seriously hate one subject to death but now ...,fear,1,seriously hate subject death feel reluctant drop
1,im so full of life i feel appalled,anger,2,m life feel appalled
2,i sit here to write i start to dig out my feel...,fear,1,sit write start dig feeling think afraid accep...
3,ive been really angry with r and i feel like a...,joy,0,ve angry r feel like idiot trust place
4,i feel suspicious if there is no one outside l...,fear,1,feel suspicious outside like rapture happen
...,...,...,...,...
5932,i begun to feel distressed for you,fear,1,begin feel distressed
5933,i left feeling annoyed and angry thinking that...,anger,2,leave feel annoyed angry thinking center stupi...
5934,i were to ever get married i d have everything...,joy,0,marry d ready offer ve get club perfect good l...
5935,i feel reluctant in applying there because i w...,fear,1,feel reluctant apply want able find company kn...
5936,i just wanted to apologize to you because i fe...,anger,2,want apologize feel like heartless bitch

In [26]:
# Do the 'train-test' splitting with test size of 20% with random state of 2022 and stratify sampling too
# Note: Use the preprocessed_Comment
X = df["preprocessed_comment"]
y = df["Emotion_num"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

**Let's check the scores with our best model till now**

-   Random Forest

**Attempt1** :

1. using the sklearn pipeline module create a classification pipeline to classify the Data.

**Note:**

-   using CountVectorizer with both unigrams and bigrams.
-   use **RandomForest** as the classifier.
-   print the classification report.

In [27]:
# 1. create a pipeline object
pipeline = Pipeline(
    [
        ("vectorizer", CountVectorizer(ngram_range=(1, 2))),
        ("model", RandomForestClassifier(n_estimators=100)),
    ]
)

# 2. fit with X_train and y_train
pipeline.fit(X_train, y_train)

# 3. get the predictions for X_test and store it in y_pred
y_hat = pipeline.predict(X_test)

# 4. print the classfication report
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.93      0.95      0.94       400
           1       0.95      0.92      0.93       388
           2       0.93      0.93      0.93       400

    accuracy                           0.94      1188
   macro avg       0.94      0.94      0.94      1188
weighted avg       0.94      0.94      0.94      1188

**Attempt 2** :

1. using the sklearn pipeline module create a classification pipeline to classify the data.

**Note:**

-   using **TF-IDF vectorizer** for pre-processing the text.
-   use **RandomForest** as the classifier.
-   print the classification report.

In [28]:
# 1. create a pipeline object
pipeline = Pipeline(
    [
        ("vectorizer", TfidfVectorizer()),
        ("model", RandomForestClassifier(n_estimators=100)),
    ]
)

# 2. fit with X_train and y_train
pipeline.fit(X_train, y_train)

# 3. get the predictions for X_test and store it in y_pred
y_hat = pipeline.predict(X_test)

# 4. print the classfication report
print(classification_report(y_test, y_hat))

              precision    recall  f1-score   support

           0       0.92      0.95      0.93       400
           1       0.92      0.93      0.92       388
           2       0.94      0.90      0.92       400

    accuracy                           0.93      1188
   macro avg       0.93      0.93      0.93      1188
weighted avg       0.93      0.93      0.93      1188