In [2]:
from pyspark.sql import SparkSession

In [3]:
spark = SparkSession.builder.appName("FilterOps").getOrCreate()
sc = spark.sparkContext
sc.setLogLevel("ERROR")
spark

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/01/21 19:27:10 WARN Utils: Your hostname, Sarveshs-MacBook-Air.local, resolves to a loopback address: 127.0.0.1; using 192.168.1.24 instead (on interface en0)
26/01/21 19:27:10 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/01/21 19:27:11 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [4]:
df = spark.read.csv(
    "datasets/students_info.csv", header=True, inferSchema=True, nullValue="NULL"
)
df.toPandas()

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19.0,M,CSE,1.0,8.1,92.0,Mumbai,Yes,No,9.876543e+09,aarav@uni.edu,650000.0,0.0
1,S002,Diya,20.0,F,EEE,2.0,NaN,88.0,Chennai,No,Yes,9.876501e+09,diya@uni.edu,480000.0,1.0
2,S003,Rohan,NaN,M,CSE,3.0,7.2,NaN,Delhi,Yes,No,NaN,rohan@uni.edu,720000.0,0.0
3,S004,Meera,21.0,F,ME,3.0,6.5,76.0,Bengaluru,None,No,9.123457e+09,None,550000.0,2.0
4,S005,Kabir,20.0,M,CIVIL,2.0,7.9,84.0,Pune,No,None,9.988777e+09,kabir@uni.edu,NaN,0.0
5,S006,Isha,19.0,F,CSE,1.0,9.0,95.0,None,Yes,Yes,9.000011e+09,isha@uni.edu,400000.0,NaN
6,S007,Aditya,22.0,M,EEE,4.0,5.8,62.0,Kolkata,No,No,NaN,aditya@uni.edu,300000.0,4.0
7,S008,Ananya,21.0,F,CSE,3.0,NaN,90.0,Hyderabad,Yes,None,9.012346e+09,ananya@uni.edu,500000.0,1.0
8,S009,Vikram,23.0,M,ME,4.0,6.1,NaN,Mumbai,No,No,9.898990e+09,None,850000.0,3.0
9,S010,Sana,20.0,F,CIVIL,2.0,8.4,93.0,Delhi,Yes,Yes,9.870001e+09,sana@uni.edu,NaN,0.0
10,S011,Neil,19.0,M,CSE,1.0,7.0,80.0,Chennai,No,No,9.871112e+09,neil@uni.edu,600000.0,NaN
11,S012,Priya,NaN,F,None,NaN,8.7,91.0,None,None,None,NaN,priya@uni.edu,NaN,0.0
12,S013,Arjun,21.0,M,CSE,3.0,7.6,85.0,Pune,None,No,9.990001e+09,arjun@uni.edu,700000.0,1.0
13,S014,Khushi,22.0,F,ME,4.0,6.9,70.0,None,No,No,9.000100e+09,khushi@uni.edu,520000.0,2.0
14,S015,Rahul,20.0,M,CIVIL,2.0,NaN,78.0,Hyderabad,Yes,No,9.887767e+09,None,490000.0,NaN
15,None,None,NaN,None,None,NaN,NaN,NaN,None,None,None,NaN,None,NaN,NaN

In [5]:
df.filter(df["age"] == 21).toPandas()

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S004,Meera,21,F,ME,3,6.5,76,Bengaluru,None,No,9123456780,None,550000,2
1,S008,Ananya,21,F,CSE,3,NaN,90,Hyderabad,Yes,None,9012345678,ananya@uni.edu,500000,1
2,S013,Arjun,21,M,CSE,3,7.6,85,Pune,None,No,9990001112,arjun@uni.edu,700000,1

# Filter

In [6]:
df.filter(df["department"] != "CIVIL").toPandas()

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19.0,M,CSE,1,8.1,92.0,Mumbai,Yes,No,9.876543e+09,aarav@uni.edu,650000,0.0
1,S002,Diya,20.0,F,EEE,2,NaN,88.0,Chennai,No,Yes,9.876501e+09,diya@uni.edu,480000,1.0
2,S003,Rohan,NaN,M,CSE,3,7.2,NaN,Delhi,Yes,No,NaN,rohan@uni.edu,720000,0.0
3,S004,Meera,21.0,F,ME,3,6.5,76.0,Bengaluru,None,No,9.123457e+09,None,550000,2.0
4,S006,Isha,19.0,F,CSE,1,9.0,95.0,None,Yes,Yes,9.000011e+09,isha@uni.edu,400000,NaN
5,S007,Aditya,22.0,M,EEE,4,5.8,62.0,Kolkata,No,No,NaN,aditya@uni.edu,300000,4.0
6,S008,Ananya,21.0,F,CSE,3,NaN,90.0,Hyderabad,Yes,None,9.012346e+09,ananya@uni.edu,500000,1.0
7,S009,Vikram,23.0,M,ME,4,6.1,NaN,Mumbai,No,No,9.898990e+09,None,850000,3.0
8,S011,Neil,19.0,M,CSE,1,7.0,80.0,Chennai,No,No,9.871112e+09,neil@uni.edu,600000,NaN
9,S013,Arjun,21.0,M,CSE,3,7.6,85.0,Pune,None,No,9.990001e+09,arjun@uni.edu,700000,1.0
10,S014,Khushi,22.0,F,ME,4,6.9,70.0,None,No,No,9.000100e+09,khushi@uni.edu,520000,2.0

In [10]:
df.filter((df["gpa"] > 8) & (df["attendance_pct"] > 70)).select(
    ["name", "gpa", "attendance_pct"]
).toPandas()

    name  gpa  attendance_pct
0  Aarav  8.1              92
1   Isha  9.0              95
2   Sana  8.4              93
3  Priya  8.7              91

In [11]:
df.filter(~((df["department"] == "CSE") & (df["gender"] == "M"))).select(
    ["name", "department", "gender"]
).toPandas()

      name department gender
0     Diya        EEE      F
1    Meera         ME      F
2    Kabir      CIVIL      M
3     Isha        CSE      F
4   Aditya        EEE      M
5   Ananya        CSE      F
6   Vikram         ME      M
7     Sana      CIVIL      F
8    Priya       None      F
9   Khushi         ME      F
10   Rahul      CIVIL      M

# Group and Aggregate

In [14]:
df.groupBy("department").count().toPandas()

  department  count
0       None      2
1      CIVIL      3
2         ME      3
3        CSE      6
4        EEE      2

In [16]:
df.select(["department", "gpa"]).groupBy("department").avg().toPandas()

  department  avg(gpa)
0       None      8.70
1      CIVIL      8.15
2         ME      6.50
3        CSE      7.78
4        EEE      5.80

In [17]:
df.groupBy("year").count().toPandas()

   year  count
0   NaN      2
1   1.0      3
2   3.0      4
3   4.0      3
4   2.0      4

In [24]:
df.agg({"age": "avg"}).toPandas()

    avg(age)
0  20.538462

## Ordering & Sorting

In [28]:
df.orderBy(df["gpa"].desc()).select(["name", "gpa"]).toPandas()

      name  gpa
0     Isha  9.0
1    Priya  8.7
2     Sana  8.4
3    Aarav  8.1
4    Kabir  7.9
5    Arjun  7.6
6    Rohan  7.2
7     Neil  7.0
8   Khushi  6.9
9    Meera  6.5
10  Vikram  6.1
11  Aditya  5.8
12    Diya  NaN
13  Ananya  NaN
14   Rahul  NaN
15    None  NaN

In [30]:
df.sort(["attendance_pct"], ascending=False).select(
    ["name", "attendance_pct"]
).toPandas()

      name  attendance_pct
0     Isha            95.0
1     Sana            93.0
2    Aarav            92.0
3    Priya            91.0
4   Ananya            90.0
5     Diya            88.0
6    Arjun            85.0
7    Kabir            84.0
8     Neil            80.0
9    Rahul            78.0
10   Meera            76.0
11  Khushi            70.0
12  Aditya            62.0
13   Rohan             NaN
14  Vikram             NaN
15    None             NaN