In [1]:
from pyspark.sql import SparkSession

In [2]:
spark = SparkSession.builder.appName("HandleMissing").getOrCreate()
sc = spark.sparkContext
sc.setLogLevel("ERROR")
spark

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
26/01/21 12:36:23 WARN Utils: Your hostname, Sarveshs-MacBook-Air.local, resolves to a loopback address: 127.0.0.1; using 192.168.1.24 instead (on interface en0)
26/01/21 12:36:23 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/01/21 12:36:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
df = spark.read.csv(
    "datasets/students_info.csv", header=True, inferSchema=True, nullValue="NULL"
)
df.toPandas()

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19.0,M,CSE,1.0,8.1,92.0,Mumbai,Yes,No,9.876543e+09,aarav@uni.edu,650000.0,0.0
1,S002,Diya,20.0,F,EEE,2.0,NaN,88.0,Chennai,No,Yes,9.876501e+09,diya@uni.edu,480000.0,1.0
2,S003,Rohan,NaN,M,CSE,3.0,7.2,NaN,Delhi,Yes,No,NaN,rohan@uni.edu,720000.0,0.0
3,S004,Meera,21.0,F,ME,3.0,6.5,76.0,Bengaluru,None,No,9.123457e+09,None,550000.0,2.0
4,S005,Kabir,20.0,M,CIVIL,2.0,7.9,84.0,Pune,No,None,9.988777e+09,kabir@uni.edu,NaN,0.0
5,S006,Isha,19.0,F,CSE,1.0,9.0,95.0,None,Yes,Yes,9.000011e+09,isha@uni.edu,400000.0,NaN
6,S007,Aditya,22.0,M,EEE,4.0,5.8,62.0,Kolkata,No,No,NaN,aditya@uni.edu,300000.0,4.0
7,S008,Ananya,21.0,F,CSE,3.0,NaN,90.0,Hyderabad,Yes,None,9.012346e+09,ananya@uni.edu,500000.0,1.0
8,S009,Vikram,23.0,M,ME,4.0,6.1,NaN,Mumbai,No,No,9.898990e+09,None,850000.0,3.0
9,S010,Sana,20.0,F,CIVIL,2.0,8.4,93.0,Delhi,Yes,Yes,9.870001e+09,sana@uni.edu,NaN,0.0
10,S011,Neil,19.0,M,CSE,1.0,7.0,80.0,Chennai,No,No,9.871112e+09,neil@uni.edu,600000.0,NaN
11,S012,Priya,NaN,F,None,NaN,8.7,91.0,None,None,None,NaN,priya@uni.edu,NaN,0.0
12,S013,Arjun,21.0,M,CSE,3.0,7.6,85.0,Pune,None,No,9.990001e+09,arjun@uni.edu,700000.0,1.0
13,S014,Khushi,22.0,F,ME,4.0,6.9,70.0,None,No,No,9.000100e+09,khushi@uni.edu,520000.0,2.0
14,S015,Rahul,20.0,M,CIVIL,2.0,NaN,78.0,Hyderabad,Yes,No,9.887767e+09,None,490000.0,NaN
15,None,None,NaN,None,None,NaN,NaN,NaN,None,None,None,NaN,None,NaN,NaN

In [12]:
df.printSchema()

root
 |-- student_id: string (nullable = true)
 |-- name: string (nullable = true)
 |-- age: integer (nullable = true)
 |-- gender: string (nullable = true)
 |-- department: string (nullable = true)
 |-- year: integer (nullable = true)
 |-- gpa: double (nullable = true)
 |-- attendance_pct: integer (nullable = true)
 |-- city: string (nullable = true)
 |-- hostel: string (nullable = true)
 |-- scholarship: string (nullable = true)
 |-- phone: long (nullable = true)
 |-- email: string (nullable = true)
 |-- parent_income: integer (nullable = true)
 |-- backlogs: integer (nullable = true)

In [4]:
df.describe().toPandas()

,summary,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,count,15,15,13,15,14,14,12,13,12,12,12,12,12,12,12
1,mean,None,None,20.53846153846154,None,None,2.5,7.433333333333334,83.38461538461539,None,None,None,9.616300463833334E9,None,563333.3333333334,1.1666666666666667
2,stddev,None,None,1.2659242088545828,None,None,1.0919284281983377,1.0236595077850779,9.82800811913297,None,None,None,4.3315895468328696E8,None,150353.11970844038,1.3371158468430429
3,min,S001,Aarav,19,F,CIVIL,1,5.8,62,Bengaluru,No,No,9000011111,aarav@uni.edu,300000,0
4,max,S015,Vikram,23,M,ME,4,9.0,95,Pune,Yes,Yes,9990001112,sana@uni.edu,850000,4

### Default Drop

In [5]:
df.na.drop().toPandas()

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19,M,CSE,1,8.1,92,Mumbai,Yes,No,9876543210,aarav@uni.edu,650000,0

### Drop (any)

In [6]:
drop_any = df.na.drop(how="any")
print(len(df.toPandas()), " -> ", len(drop_any.toPandas()))
drop_any.toPandas()

16  ->  1

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19,M,CSE,1,8.1,92,Mumbai,Yes,No,9876543210,aarav@uni.edu,650000,0

### Drop (all)

In [7]:
drop_all = df.na.drop(how="all")
print(len(df.toPandas()), " -> ", len(drop_all.toPandas()))
drop_all.toPandas()

16  ->  15

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19.0,M,CSE,1.0,8.1,92.0,Mumbai,Yes,No,9.876543e+09,aarav@uni.edu,650000.0,0.0
1,S002,Diya,20.0,F,EEE,2.0,NaN,88.0,Chennai,No,Yes,9.876501e+09,diya@uni.edu,480000.0,1.0
2,S003,Rohan,NaN,M,CSE,3.0,7.2,NaN,Delhi,Yes,No,NaN,rohan@uni.edu,720000.0,0.0
3,S004,Meera,21.0,F,ME,3.0,6.5,76.0,Bengaluru,None,No,9.123457e+09,None,550000.0,2.0
4,S005,Kabir,20.0,M,CIVIL,2.0,7.9,84.0,Pune,No,None,9.988777e+09,kabir@uni.edu,NaN,0.0
5,S006,Isha,19.0,F,CSE,1.0,9.0,95.0,None,Yes,Yes,9.000011e+09,isha@uni.edu,400000.0,NaN
6,S007,Aditya,22.0,M,EEE,4.0,5.8,62.0,Kolkata,No,No,NaN,aditya@uni.edu,300000.0,4.0
7,S008,Ananya,21.0,F,CSE,3.0,NaN,90.0,Hyderabad,Yes,None,9.012346e+09,ananya@uni.edu,500000.0,1.0
8,S009,Vikram,23.0,M,ME,4.0,6.1,NaN,Mumbai,No,No,9.898990e+09,None,850000.0,3.0
9,S010,Sana,20.0,F,CIVIL,2.0,8.4,93.0,Delhi,Yes,Yes,9.870001e+09,sana@uni.edu,NaN,0.0
10,S011,Neil,19.0,M,CSE,1.0,7.0,80.0,Chennai,No,No,9.871112e+09,neil@uni.edu,600000.0,NaN
11,S012,Priya,NaN,F,None,NaN,8.7,91.0,None,None,None,NaN,priya@uni.edu,NaN,0.0
12,S013,Arjun,21.0,M,CSE,3.0,7.6,85.0,Pune,None,No,9.990001e+09,arjun@uni.edu,700000.0,1.0
13,S014,Khushi,22.0,F,ME,4.0,6.9,70.0,None,No,No,9.000100e+09,khushi@uni.edu,520000.0,2.0
14,S015,Rahul,20.0,M,CIVIL,2.0,NaN,78.0,Hyderabad,Yes,No,9.887767e+09,None,490000.0,NaN

### Drop (w/ threshold)

In [8]:
drop_threshold = df.na.drop(how="any", thresh=8)
print(len(df.toPandas()), " -> ", len(drop_threshold.toPandas()))
drop_threshold.toPandas()

16  ->  14

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19.0,M,CSE,1,8.1,92.0,Mumbai,Yes,No,9.876543e+09,aarav@uni.edu,650000.0,0.0
1,S002,Diya,20.0,F,EEE,2,NaN,88.0,Chennai,No,Yes,9.876501e+09,diya@uni.edu,480000.0,1.0
2,S003,Rohan,NaN,M,CSE,3,7.2,NaN,Delhi,Yes,No,NaN,rohan@uni.edu,720000.0,0.0
3,S004,Meera,21.0,F,ME,3,6.5,76.0,Bengaluru,None,No,9.123457e+09,None,550000.0,2.0
4,S005,Kabir,20.0,M,CIVIL,2,7.9,84.0,Pune,No,None,9.988777e+09,kabir@uni.edu,NaN,0.0
5,S006,Isha,19.0,F,CSE,1,9.0,95.0,None,Yes,Yes,9.000011e+09,isha@uni.edu,400000.0,NaN
6,S007,Aditya,22.0,M,EEE,4,5.8,62.0,Kolkata,No,No,NaN,aditya@uni.edu,300000.0,4.0
7,S008,Ananya,21.0,F,CSE,3,NaN,90.0,Hyderabad,Yes,None,9.012346e+09,ananya@uni.edu,500000.0,1.0
8,S009,Vikram,23.0,M,ME,4,6.1,NaN,Mumbai,No,No,9.898990e+09,None,850000.0,3.0
9,S010,Sana,20.0,F,CIVIL,2,8.4,93.0,Delhi,Yes,Yes,9.870001e+09,sana@uni.edu,NaN,0.0
10,S011,Neil,19.0,M,CSE,1,7.0,80.0,Chennai,No,No,9.871112e+09,neil@uni.edu,600000.0,NaN
11,S013,Arjun,21.0,M,CSE,3,7.6,85.0,Pune,None,No,9.990001e+09,arjun@uni.edu,700000.0,1.0
12,S014,Khushi,22.0,F,ME,4,6.9,70.0,None,No,No,9.000100e+09,khushi@uni.edu,520000.0,2.0
13,S015,Rahul,20.0,M,CIVIL,2,NaN,78.0,Hyderabad,Yes,No,9.887767e+09,None,490000.0,NaN

### Drop (subset)

In [9]:
df_subset = df.na.drop(how="any", subset=["gpa"])
print(len(df.toPandas()), " -> ", len(df_subset.toPandas()))
df_subset.toPandas()

16  ->  12

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19.0,M,CSE,1.0,8.1,92.0,Mumbai,Yes,No,9.876543e+09,aarav@uni.edu,650000.0,0.0
1,S003,Rohan,NaN,M,CSE,3.0,7.2,NaN,Delhi,Yes,No,NaN,rohan@uni.edu,720000.0,0.0
2,S004,Meera,21.0,F,ME,3.0,6.5,76.0,Bengaluru,None,No,9.123457e+09,None,550000.0,2.0
3,S005,Kabir,20.0,M,CIVIL,2.0,7.9,84.0,Pune,No,None,9.988777e+09,kabir@uni.edu,NaN,0.0
4,S006,Isha,19.0,F,CSE,1.0,9.0,95.0,None,Yes,Yes,9.000011e+09,isha@uni.edu,400000.0,NaN
5,S007,Aditya,22.0,M,EEE,4.0,5.8,62.0,Kolkata,No,No,NaN,aditya@uni.edu,300000.0,4.0
6,S009,Vikram,23.0,M,ME,4.0,6.1,NaN,Mumbai,No,No,9.898990e+09,None,850000.0,3.0
7,S010,Sana,20.0,F,CIVIL,2.0,8.4,93.0,Delhi,Yes,Yes,9.870001e+09,sana@uni.edu,NaN,0.0
8,S011,Neil,19.0,M,CSE,1.0,7.0,80.0,Chennai,No,No,9.871112e+09,neil@uni.edu,600000.0,NaN
9,S012,Priya,NaN,F,None,NaN,8.7,91.0,None,None,None,NaN,priya@uni.edu,NaN,0.0
10,S013,Arjun,21.0,M,CSE,3.0,7.6,85.0,Pune,None,No,9.990001e+09,arjun@uni.edu,700000.0,1.0
11,S014,Khushi,22.0,F,ME,4.0,6.9,70.0,None,No,No,9.000100e+09,khushi@uni.edu,520000.0,2.0

In [11]:
df.na.fill(0, ["gpa"]).toPandas()

,student_id,name,age,gender,department,year,gpa,attendance_pct,city,hostel,scholarship,phone,email,parent_income,backlogs
0,S001,Aarav,19.0,M,CSE,1.0,8.1,92.0,Mumbai,Yes,No,9.876543e+09,aarav@uni.edu,650000.0,0.0
1,S002,Diya,20.0,F,EEE,2.0,0.0,88.0,Chennai,No,Yes,9.876501e+09,diya@uni.edu,480000.0,1.0
2,S003,Rohan,NaN,M,CSE,3.0,7.2,NaN,Delhi,Yes,No,NaN,rohan@uni.edu,720000.0,0.0
3,S004,Meera,21.0,F,ME,3.0,6.5,76.0,Bengaluru,None,No,9.123457e+09,None,550000.0,2.0
4,S005,Kabir,20.0,M,CIVIL,2.0,7.9,84.0,Pune,No,None,9.988777e+09,kabir@uni.edu,NaN,0.0
5,S006,Isha,19.0,F,CSE,1.0,9.0,95.0,None,Yes,Yes,9.000011e+09,isha@uni.edu,400000.0,NaN
6,S007,Aditya,22.0,M,EEE,4.0,5.8,62.0,Kolkata,No,No,NaN,aditya@uni.edu,300000.0,4.0
7,S008,Ananya,21.0,F,CSE,3.0,0.0,90.0,Hyderabad,Yes,None,9.012346e+09,ananya@uni.edu,500000.0,1.0
8,S009,Vikram,23.0,M,ME,4.0,6.1,NaN,Mumbai,No,No,9.898990e+09,None,850000.0,3.0
9,S010,Sana,20.0,F,CIVIL,2.0,8.4,93.0,Delhi,Yes,Yes,9.870001e+09,sana@uni.edu,NaN,0.0
10,S011,Neil,19.0,M,CSE,1.0,7.0,80.0,Chennai,No,No,9.871112e+09,neil@uni.edu,600000.0,NaN
11,S012,Priya,NaN,F,None,NaN,8.7,91.0,None,None,None,NaN,priya@uni.edu,NaN,0.0
12,S013,Arjun,21.0,M,CSE,3.0,7.6,85.0,Pune,None,No,9.990001e+09,arjun@uni.edu,700000.0,1.0
13,S014,Khushi,22.0,F,ME,4.0,6.9,70.0,None,No,No,9.000100e+09,khushi@uni.edu,520000.0,2.0
14,S015,Rahul,20.0,M,CIVIL,2.0,0.0,78.0,Hyderabad,Yes,No,9.887767e+09,None,490000.0,NaN
15,None,None,NaN,None,None,NaN,0.0,NaN,None,None,None,NaN,None,NaN,NaN

In [22]:
from pyspark.ml.feature import Imputer

cols = ["age", "attendance_pct"]

imputer = Imputer(
    inputCols=cols, outputCols=[f"temp_{col}" for col in cols], strategy="median"
)

In [23]:
df_imputed = imputer.fit(df).transform(df)
df_imputed.select(cols + [f"temp_{col}" for col in cols]).toPandas()

     age  attendance_pct  temp_age  temp_attendance_pct
0   19.0            92.0        19                   92
1   20.0            88.0        20                   88
2    NaN             NaN        20                   85
3   21.0            76.0        21                   76
4   20.0            84.0        20                   84
5   19.0            95.0        19                   95
6   22.0            62.0        22                   62
7   21.0            90.0        21                   90
8   23.0             NaN        23                   85
9   20.0            93.0        20                   93
10  19.0            80.0        19                   80
11   NaN            91.0        20                   91
12  21.0            85.0        21                   85
13  22.0            70.0        22                   70
14  20.0            78.0        20                   78
15   NaN             NaN        20                   85